dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install pytest-cov
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
addons:
  apt:
    packages:
      - xdg-user-dirs
      - automake
      - autoconf
      - build-essential
      - libass-dev
      - libfreetype6-dev
      - libtheora-dev
      - libtool
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libxcb1-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - libfdk-aac-dev
      - libopus-dev
      - pkg-config
      - texinfo
      - zlib1g-dev
      - yasm
      - nasm
      - libmp3lame-dev
      - libav-tools
install:
  - pip install -e .
  - chmod 755 ~/bin/ffmpeg
  - xdg-user-dirs-update
script: python -m pytest test --cov=.
after_success:
  - pip install codecov
  - codecov
